package io.github.easy4j.openclaw.api;

import io.github.easy4j.openclaw.api.model.HookRequest;

import java.util.Locale;
import java.util.Objects;
import java.util.UUID;
import java.util.regex.Pattern;

/**
 * OpenClaw Gateway {@code POST /hooks/agent} {@code sessionKey} naming utility.
 * <p>
 * with Gateway {@code hooks:} aligned(See OpenClaw {@code resolveHookSessionKey}):
 * </p>
 * <ul>
 * <li><b>stable session</b>(multi-turn conversation):{@code hook:<agentId>:<peerId>}</li>
 * <li><b> + peer</b>:{@code hook:<peerId>:<correlationId>}( correlationId → session)</li>
 * <li><b> + peer</b>:request body<b></b> {@code sessionKey},generated by Gateway {@code hook:<uuid>}</li>
 * </ul>
 * <p>
 * {@code sessionKey} Gateway {@code hooks.allowRequestSessionKey=true},
 * {@code hooks.allowedSessionKeyPrefixes}( {@code hook:}).
 * </p>
 *
 * @author <a href="https://github.com/loong10k">Loong Wan</a>
 * @since 3.0.0
 */
public final class OpenClawSessionKeys {

 /** /,,,128bytes */
    private static final Pattern SAFE_SEGMENT = Pattern.compile("^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$");

    private OpenClawSessionKeys() {
    }

    /**
 * session:{@code hook:<agentId>:<peerId>}.
     *
 * @param agentId agent, {@link HookRequest#setAgentId}
 * @param peerId business peer( userId, id);Must not contain {@code :}
     */
    public static String forStableSession(String agentId, String peerId) {
        return "hook:" + normalizeSegment(agentId, "agentId") + ":"
                + normalizeSegment(peerId, "peerId");
    }

    /**
 * ephemeral session( peer):{@code hook:<peerId>:<correlationId>}.
     *
 * @param peerId business peer;Must not contain {@code :}
 * @param correlationId unique per invocation id( UUID);Must not contain {@code :}
     */
    public static String forEphemeralPeer(String peerId, String correlationId) {
        return "hook:" + normalizeSegment(peerId, "peerId") + ":"
                + normalizeSegment(correlationId, "correlationId");
    }

    /**
 * ephemeral session( peer),auto-generated {@link #newCorrelationId} correlationId.
     *
 * @param peerId business peer;Must not contain {@code :}
     */
    public static String forEphemeralPeer(String peerId) {
        return forEphemeralPeer(peerId, newCorrelationId());
    }

    /**
 * Hook correlation (UUID),Used for {@link #forEphemeralPeer(String, String)}.
     */
    public static String newCorrelationId() {
        return UUID.randomUUID().toString();
    }

    /**
 * Normalizes hook session :trim, {@code :} characters.
     */
    static String normalizeSegment(String value, String fieldName) {
        Objects.requireNonNull(value, fieldName);
        String normalized = value.trim().toLowerCase(Locale.ROOT);
        if (normalized.isEmpty()) {
            throw new IllegalArgumentException(fieldName + " must not be blank");
        }
        if (normalized.contains(":")) {
            throw new IllegalArgumentException(fieldName + " must not contain ':'");
        }
        if (!SAFE_SEGMENT.matcher(normalized).matches()) {
            throw new IllegalArgumentException(fieldName + " contains illegal characters: " + value);
        }
        return normalized;
    }
}
